### ISSUE TITLE
options['useConfigFile'] is an invalid additional property

### ISSUE THREAD

**Issue by ferrinweb** [ITCNZ/mynuxt#1]
Failed to compile with 6 errors, and all of them ocurred for the one reason what like this issue title said.

**Comment by ITCNZ** [comment]
@ferrinweb   Can you speak Chinese?

**Comment by ferrinweb** [comment]
执行'yarn run dev'产生6个报错，最终原因都是题目里所述的：options['useConfigFile'] is an invalid additional property

**Comment by ferrinweb** [comment]
错误信息：
`error  in ./node_modules/quill/dist/quill.core.css

Module build failed: ValidationError: PostCSS Loader Invalid Options

options['useConfigFile'] is an invalid additional property


 @ ./node_modules/quill/dist/quill.core.css 4:14-123 13:3-17:5 14:22-131
 @ ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["D://www//nuxt-vue-ssr-demo//node_modules//babel-preset-vue-app//dist//index.common.js",{"targets":{"ie":9,"uglify":t
rue}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./layouts/edit.vue
 @ ./layouts/edit.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js
`

**Comment by ITCNZ** [comment]
@ferrinweb  你用npm  安装一下

**Comment by ferrinweb** [comment]
确实可以了，出现新的错误：
`> node listrouter
mongodb 连接成功!
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at write_ (_http_outgoing.js:625:15)
    at ServerResponse.write (_http_outgoing.js:620:10)
    at Request.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (D:\www\nuxt-vue-ssr-demo\node_modules\request\request.js:1082:12)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at IncomingMessage.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`
增删改查操作接口都报错，啥原因？

**Comment by ferrinweb** [comment]
好像是接口返回完成后报的错，因为接口是可以返回内容的，报错之后服务就挂了。

**Comment by ITCNZ** [comment]
@ferrinweb  你确定MongoDB安装好了，也启动了？  接口返回数据了报错？不会吧

**Comment by ferrinweb** [comment]
数据库已连接，因为MongDB的控制台是有查询输出的
node 版本 8.9.4
npm 版本 5.6.0
![tim 20180323125334](https://user-images.githubusercontent.com/3353839/37812115-3d29bd0c-2e99-11e8-8dc0-089903b13db0.png)

**Comment by ferrinweb** [comment]
具体看一下表现：
1、我启动了服务，打开了页面，然后我点击查看文章按钮，页面跳转至文章列表按钮，返回正常。但是此时后台服务其实已经挂了。具体各方输出如下
前台：
![nuxt](https://user-images.githubusercontent.com/3353839/37813343-b75da43e-2e9f-11e8-8fb9-deeb906796e4.png)

MongoDB：
![mongodb](https://user-images.githubusercontent.com/3353839/37813360-c3ce699c-2e9f-11e8-9e00-9d244f656bc6.png)

Node Server：
![node](https://user-images.githubusercontent.com/3353839/37813372-cf3f9e5e-2e9f-11e8-9534-db3374bca7eb.png)

这样应该比较直观了。

**Comment by ITCNZ** [comment]
@ferrinweb  前台能不能发布文章？能不能看到文章列表？如果可以你再用supervisor listrouter 这个命令试下启动服务器

**Comment by ITCNZ** [comment]
@ferrinweb   兄弟，你重新clone下代码，是我之前的跨域写的有问题

**Comment by ferrinweb** [comment]
我换了目录重新clone了，还是不行，一样的问题。
supervisor 是什么？

**Comment by ITCNZ** [comment]
@ferrinweb  是一个实时刷新的包， 你全局安装一下 sudo pip install supervisor

**Comment by ITCNZ** [comment]
@ferrinweb 是一个实时刷新的包， 你全局安装一下sudo npm install -g supervisor

**Comment by ferrinweb** [comment]
兄弟，加了supervisor是可以的，但是**并没有从根本上解决问题**，报错依然存在，仅仅是进程挂了重启而已。

**Comment by ITCNZ** [comment]
报错还一样？ 你重新clone代码，然后重新npm  要是还不行那就无解了，我这边正常..
