### ISSUE TITLE
连接不上服务器，求解决

### ISSUE THREAD

**Issue by xumeihong** [ITCNZ/mynuxt#7]
DONE  Compiled successfully in 63ms                                                                                                                                                                                                 16:32:55

 OPEN  http://localhost:3389

  nuxt:render Rendering url / +0ms
  nuxt:render Rendering url /login +397ms
当前服务器地址.... { url: { api: 'http://localhost:3000/api' }, env: 'localhost' }
  nuxt:render Data fetching /login: 0ms +0ms

 ERROR

  Error: connect ECONNREFUSED 127.0.0.1:3000

  - net.js:1191 TCPConnectWrap.afterConnect [as oncomplete]
    net.js:1191:14

我用npm install安装了依赖  然后用npm run dev运行    显示端口号是3389    但是api接口的端口号是3000    报错信息如上   虽然能正常显示登录页面   但是没办法登录进去  控制台报错信息如下
Failed to load resource: net::ERR_CONNECTION_REFUSED
E:\xampp\htdocs\mynuxt-master\node_modules\_axios@0.16.2@axios\lib\core\createError.js:16 Uncaught (in promise) Error: Network Error
    at createError (E:\xampp\htdocs\mynuxt-master\node_modules\_axios@0.16.2@axios\lib\core\createError.js:16)
    at XMLHttpRequest.handleError (E:\xampp\htdocs\mynuxt-master\node_modules\_axios@0.16.2@axios\lib\adapters\xhr.js:87)

**Comment by ITCNZ** [comment]
没有启动接口服务
